### ISSUE TITLE
Lua Error: attempt to index field 'KeypadData' (a nil value)

### ISSUE THREAD

**Issue by AMD-NICK** [willox/gmod-keypad#15]
ServerLog: Ryder Johnson (STEAM_0:0:27xxx361) Attempted to use tool keypad_willox
L 07/23/2015 - 19:03:00: Ryder Johnson (STEAM_0:0:27xxx361) Attempted to use tool keypad_willox
ServerLog: Ryder Johnson (STEAM_0:0:27xxx361) Attempted to use tool keypad_willox
L 07/23/2015 - 19:03:01: Ryder Johnson (STEAM_0:0:27xxx361) Attempted to use tool keypad_willox
L 07/23/2015 - 19:03:01: Lua Error: 
[ERROR] addons/keypad-github/lua/weapons/gmod_tool/stools/keypad_willox.lua:87: attempt to index field 'KeypadData' (a nil value)
1. RightClick - addons/keypad-github/lua/weapons/gmod_tool/stools/keypad_willox.lua:87
   1. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:281

**Comment by AMD-NICK** [comment]
Up
```
[ERROR] addons/keypad-github/lua/weapons/gmod_tool/stools/keypad_willox.lua:87: attempt to index field 'KeypadData' (a nil value)
  1. RightClick - addons/keypad-github/lua/weapons/gmod_tool/stools/keypad_willox.lua:87
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:281
```

**Comment by AntoineAngel** [comment]
L 05/26/2016 - 19:16:21: Lua Error: 
[ERROR] lua/weapons/gmod_tool/stools/keypad_willox.lua:87: attempt to index field 'KeypadData' (a nil value)
  1. RightClick - lua/weapons/gmod_tool/stools/keypad_willox.lua:87
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:281

**Comment by willox** [comment]
This might be fixed
