### ISSUE TITLE
Advanced Duplicator support

### ISSUE THREAD

**Issue by insanekid2** [willox/gmod-keypad#5]
Can we get it?

Every time its pasted from an advanced dupe, it just defaults to 1337, as well as not activating anything.

**Comment by DSHADOWK** [comment]
Just code it:
-- Handling Duplications
local function dooEet(ply, ent, stuff)
	if (ent.isFadingDoor) then
		ent:fadeDeactivate();
		onRemove(ent)
	else
		ent.isFadingDoor = true;
		ent.fadeActivate = fadeActivate;
		ent.fadeDeactivate = fadeDeactivate;
		ent.fadeToggleActive = fadeToggleActive;
		ent:CallOnRemove("Fading Door", onRemove);
		if (WireLib) then
			doWireInputs(ent);
			doWireOutputs(ent);
			ent.fadeTriggerInput = ent.fadeTriggerInput or ent.TriggerInput;
			ent.TriggerInput = TriggerInput;
			if (not ent.IsWire) then -- Dupe Support
				ent.fadePreEntityCopy = ent.PreEntityCopy;
				ent.PreEntityCopy = PreEntityCopy;
				ent.fadePostEntityPaste = ent.PostEntityPaste;
				ent.PostEntityPaste = PostEntityPaste;
			end				
		end
	end
	ent.fadeUpNum = numpad.OnUp(ply, stuff.key, "Fading Door onUp", ent);
	ent.fadeDownNum = numpad.OnDown(ply, stuff.key, "Fading Door onDown", ent);
	ent.fadeToggle = stuff.toggle;
	ent.noEffect = stuff.noeffect;
	if (stuff.reversed) then
		ent:fadeActivate();
	end
	duplicator.StoreEntityModifier(ent, "Fading Door", stuff);
	return true;
end

duplicator.RegisterEntityModifier("Fading Door", dooEet);

- Example from Fading door.

**Comment by Jophes** [comment]
Also wanted this, created fork and fixed the issue. Review pull request #18
